### Запросить все очки
GET http://localhost:8080/users/
Content-Type: application/json


### Создать пользователя
POST http://localhost:8080/users/
Content-Type: application/json

{
    "username": "yura"
}

### Обновить очки пользователя
PUT http://localhost:8080/users/scores/
Content-Type: application/json

{
    "username": "yura",
    "score": 1500
}
