name: tetris_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.0
  drift: ^2.25.1
  talker: ^4.6.14

dev_dependencies:
  drift_dev: ^2.25.2
  build_runner:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^5.1.0
