# Директория с ARB-файлами
arb-dir: lib/l10n 

# Шаблон ARB-файла, содержащий параметры с описанием строк
template-arb-file: app_en.arb 

# Директория для генерируемых файлов
output-dir: lib/l10n/gen 

# Корневой генерируемый файл локализации, который будет
# использоваться в приложении
output-localization-file: app_localizations.dart

# Метод доступа к строкам через of(context) будет
# возвращять null-safety строку (String, а не String?)
nullable-getter: false

# Классы, которые не будут генерироваться
# Данное ствойство локализатора скоре перестанет поддерживаться,
# поэтому стелим солому заранее
synthetic-package: false
